namespace DMSPortal.Models.Enums;

public enum EFunctionCode
{
    GENERAL,
    GENERAL_ATTENDANCE,
    GENERAL_BRANCH,
    GENERAL_CLASS,
    GENERAL_NOTE,
    GENERAL_PITCH,
    GENERAL_PITCH_GROUP,
    GENERAL_SHIFT,
    GENERAL_STUDENT,

    STATISTIC,

    SYSTEM,
    SYSTEM_USER,
    SYSTEM_ROLE,
    SYSTEM_FUNCTION,
    SYSTEM_COMMAND,
    SYSTEM_PERMISSION,
}