version: '3.8'

services:
  dms.cache:
    image: redis:7.0.15-alpine
    container_name: dms.cache
    restart: always
    ports:
      - "6379:6379"

  dms.db:
    image: postgres:alpine3.16
    container_name: dms.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=DMSPortalDB
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

  dms.seq:
    image: datalust/seq:latest
    container_name: eventhub.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data
  
  dms.hangfire:
    image: mongo
    container_name: dms.hangfire
    ports:
      - "27018:27017"
    volumes:
      - hangfire_mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      

# network section
networks:
  default:
    name: dms
    driver: bridge

# volumes section
volumes:
  postgres_data:
    name: postgres_data
  seq_data:
    name: seq_data
  pgadmin_data:
    name: pgadmin_data
  hangfire_mongo_data:
    name: hangfire_mongo_data